use std::collections::HashMap;


pub fn get_cartridge_types() -> HashMap<u8, &'static str> {
    let mut map = HashMap::new();

    map.insert(0x00, "ROM ONLY");
    map.insert(0x01, "MBC1");
    map.insert(0x02, "MBC1+RAM");
    map.insert(0x03, "MBC1+RAM+BATTERY");
    map.insert(0x05, "MBC2");
    map.insert(0x06, "MBC2+BATTERY");
    map.insert(0x08, "ROM+RAM 9");
    map.insert(0x09, "ROM+RAM+BATTERY 9");
    map.insert(0x0B, "MMM01");
    map.insert(0x0C, "MMM01+RAM");
    map.insert(0x0D, "MMM01+RAM+BATTERY");
    map.insert(0x0F, "MBC3+TIMER+BATTERY");
    map.insert(0x10, "MBC3+TIMER+RAM+BATTERY 10");
    map.insert(0x11, "MBC3");
    map.insert(0x12, "MBC3+RAM 10");
    map.insert(0x13, "MBC3+RAM+BATTERY 10");
    map.insert(0x19, "MBC5");
    map.insert(0x1A, "MBC5+RAM");
    map.insert(0x1B, "MBC5+RAM+BATTERY");
    map.insert(0x1C, "MBC5+RUMBLE");
    map.insert(0x1D, "MBC5+RUMBLE+RAM");
    map.insert(0x1E, "MBC5+RUMBLE+RAM+BATTERY");
    map.insert(0x20, "MBC6");
    map.insert(0x22, "MBC7+SENSOR+RUMBLE+RAM+BATTERY");
    map.insert(0xFC, "POCKET CAMERA");
    map.insert(0xFD, "BANDAI TAMA5");
    map.insert(0xFE, "HuC3");
    map.insert(0xFF, "HuC1+RAM+BATTERY");

    map
}

pub fn old_licensee_codes() -> HashMap<u8, &'static str> {
    let mut map = HashMap::new();

    map.insert(0x00, "None");
    map.insert(0x01, "Nintendo");
    map.insert(0x08, "Capcom");
    map.insert(0x09, "HOT-B");
    map.insert(0x0A, "Jaleco");
    map.insert(0x0B, "Coconuts Japan");
    map.insert(0x0C, "Elite Systems");
    map.insert(0x13, "EA (Electronic Arts)");
    map.insert(0x18, "Hudson Soft");
    map.insert(0x19, "ITC Entertainment");
    map.insert(0x1A, "Yanoman");
    map.insert(0x1D, "Japan Clary");
    map.insert(0x1F, "Virgin Games Ltd.3");
    map.insert(0x24, "PCM Complete");
    map.insert(0x25, "San-X");
    map.insert(0x28, "Kemco");
    map.insert(0x29, "SETA Corporation");
    map.insert(0x30, "Infogrames5");
    map.insert(0x31, "Nintendo");
    map.insert(0x32, "Bandai");
    map.insert(0x33, "Indicates that the New licensee code should be used instead.");
    map.insert(0x34, "Konami");
    map.insert(0x35, "HectorSoft");
    map.insert(0x38, "Capcom");
    map.insert(0x39, "Banpresto");
    map.insert(0x3C, "Entertainment Interactive (stub)");
    map.insert(0x3E, "Gremlin");
    map.insert(0x41, "Ubi Soft1");
    map.insert(0x42, "Atlus");
    map.insert(0x44, "Malibu Interactive");
    map.insert(0x46, "Angel");
    map.insert(0x47, "Spectrum HoloByte");
    map.insert(0x49, "Irem");
    map.insert(0x4A, "Virgin Games Ltd.3");
    map.insert(0x4D, "Malibu Interactive");
    map.insert(0x4F, "U.S. Gold");
    map.insert(0x50, "Absolute");
    map.insert(0x51, "Acclaim Entertainment");
    map.insert(0x52, "Activision");
    map.insert(0x53, "Sammy USA Corporation");
    map.insert(0x54, "GameTek");
    map.insert(0x55, "Park Place13");
    map.insert(0x56, "LJN");
    map.insert(0x57, "Matchbox");
    map.insert(0x59, "Milton Bradley Company");
    map.insert(0x5A, "Mindscape");
    map.insert(0x5B, "Romstar");
    map.insert(0x5C, "Naxat Soft14");
    map.insert(0x5D, "Tradewest");
    map.insert(0x60, "Titus Interactive");
    map.insert(0x61, "Virgin Games Ltd.3");
    map.insert(0x67, "Ocean Software");
    map.insert(0x69, "EA (Electronic Arts)");
    map.insert(0x6E, "Elite Systems");
    map.insert(0x6F, "Electro Brain");
    map.insert(0x70, "Infogrames5");
    map.insert(0x71, "Interplay Entertainment");
    map.insert(0x72, "Broderbund");
    map.insert(0x73, "Sculptured Software6");
    map.insert(0x75, "The Sales Curve Limited7");
    map.insert(0x78, "THQ");
    map.insert(0x79, "Accolade15");
    map.insert(0x7A, "Triffix Entertainment");
    map.insert(0x7C, "MicroProse");
    map.insert(0x7F, "Kemco");
    map.insert(0x80, "Misawa Entertainment");
    map.insert(0x83, "LOZC G.");
    map.insert(0x86, "Tokuma Shoten");
    map.insert(0x8B, "Bullet-Proof Software2");
    map.insert(0x8C, "Vic Tokai Corp.16");
    map.insert(0x8E, "Ape Inc.17");
    map.insert(0x8F, "I’Max18");
    map.insert(0x91, "Chunsoft Co.8");
    map.insert(0x92, "Video System");
    map.insert(0x93, "Tsubaraya Productions");
    map.insert(0x95, "Varie");
    map.insert(0x96, "Yonezawa19/S’Pal");
    map.insert(0x97, "Kemco");
    map.insert(0x99, "Arc");
    map.insert(0x9A, "Nihon Bussan");
    map.insert(0x9B, "Tecmo");
    map.insert(0x9C, "Imagineer");
    map.insert(0x9D, "Banpresto");
    map.insert(0x9F, "Nova");
    map.insert(0xA1, "Hori Electric");
    map.insert(0xA2, "Bandai");
    map.insert(0xA4, "Konami");
    map.insert(0xA6, "Kawada");
    map.insert(0xA7, "Takara");
    map.insert(0xA9, "Technos Japan");
    map.insert(0xAA, "Broderbund");
    map.insert(0xAC, "Toei Animation");
    map.insert(0xAD, "Toho");
    map.insert(0xAF, "Namco");
    map.insert(0xB0, "Acclaim Entertainment");
    map.insert(0xB1, "ASCII Corporation or Nexsoft");
    map.insert(0xB2, "Bandai");
    map.insert(0xB4, "Square Enix");
    map.insert(0xB6, "HAL Laboratory");
    map.insert(0xB7, "SNK");
    map.insert(0xB9, "Pony Canyon");
    map.insert(0xBA, "Culture Brain");
    map.insert(0xBB, "Sunsoft");
    map.insert(0xBD, "Sony Imagesoft");
    map.insert(0xBF, "Sammy Corporation");
    map.insert(0xC0, "Taito");
    map.insert(0xC2, "Kemco");
    map.insert(0xC3, "Square");
    map.insert(0xC4, "Tokuma Shoten");
    map.insert(0xC5, "Data East");
    map.insert(0xC6, "Tonkin House");
    map.insert(0xC8, "Koei");
    map.insert(0xC9, "UFL");
    map.insert(0xCA, "Ultra Games");
    map.insert(0xCB, "VAP, Inc.");
    map.insert(0xCC, "Use Corporation");
    map.insert(0xCD, "Meldac");
    map.insert(0xCE, "Pony Canyon");
    map.insert(0xCF, "Angel");
    map.insert(0xD0, "Taito");
    map.insert(0xD1, "SOFEL (Software Engineering Lab)");
    map.insert(0xD2, "Quest");
    map.insert(0xD3, "Sigma Enterprises");
    map.insert(0xD4, "ASK Kodansha Co.");
    map.insert(0xD6, "Naxat Soft14");
    map.insert(0xD7, "Copya System");
    map.insert(0xD9, "Banpresto");
    map.insert(0xDA, "Tomy");
    map.insert(0xDB, "LJN");
    map.insert(0xDD, "Nippon Computer Systems");
    map.insert(0xDE, "Human Ent.");
    map.insert(0xDF, "Altron");
    map.insert(0xE0, "Jaleco");
    map.insert(0xE1, "Towa Chiki");
    map.insert(0xE2, "Yutaka # Needs more info");
    map.insert(0xE3, "Varie");
    map.insert(0xE5, "Epoch");
    map.insert(0xE7, "Athena");
    map.insert(0xE8, "Asmik Ace Entertainment");
    map.insert(0xE9, "Natsume");
    map.insert(0xEA, "King Records");
    map.insert(0xEB, "Atlus");
    map.insert(0xEC, "Epic/Sony Records");
    map.insert(0xEE, "IGS");
    map.insert(0xF0, "A Wave");
    map.insert(0xF3, "Extreme Entertainment");
    map.insert(0xFF, "LJN");

    map
}
